
modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "twilightgear"
version = "${file.jarVersion}"
displayName = "Twilight Gear"
credits = "Thanks to SilentChaos for SilentGear and Benimatic for Twilight Forest, and the many others, who contributed to both projects!"
authors = "farinc"
logoFile = "logo.png"
description = '''
A small addon mod for Silent Gear that provides Twilight Forest inspired materials.
'''
[[dependencies.twilightgear]]
modId = "forge"
mandatory = true
versionRange = "[40.2.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.twilightgear]]
modId = "silentgear"
mandatory = true
versionRange = "[2.10,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.twilightgear]]
modId = "twilightforest"
mandatory = true
versionRange = "[4.1,4.2)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.twilightgear]]
modId = "moremcmeta"
mandatory = true
versionRange = "[1.18.2-4.2,1.18.2-4.3)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.twilightgear]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
